### ISSUE TITLE
Load Translator object into a single HTML

### ISSUE THREAD

**Issue by merolhack** [php-gettext/JS-Translator#1]
Hi, how can i use/load the Translator object(Global JS) into a single HTML page without Webpack?

My code is:

```
<script src="assets/js/sprintf.min.js"></script>
<script src="assets/js/translator.js"></script>
<script>
(function() {
    'use strict';       
    console.log( Translator );
})();
</script>
```

It shows me at the console the next Error:

> Uncaught ReferenceError: Translator is not defined

**Comment by oscarotero** [comment]
The translator class is exposed into the `gettext` variable, as showed here: https://github.com/oscarotero/gettext-translator/blob/master/src/translator.js#L14

But maybe you're right and this could be changed to `Translator`. I'm going to change it.

**Comment by oscarotero** [comment]
Fixed
