### ISSUE TITLE
Problem if Content Security Policy (CSP) does not allow eval

### ISSUE THREAD

**Issue by mehdibenyounes** [php-gettext/JS-Translator#4]
https://github.com/oscarotero/gettext-translator/blob/78c7bd74bb1d3a532cdc93489c00d972a18ee9de/src/translator.js#L172

The problem is caused by : `new Function()`

We must find another solution to no longer use eval functions !

**Comment by mehdibenyounes** [comment]
I'm trying to find a solution, but I can not do it right now. And you ?

**Comment by oscarotero** [comment]
I cannot do it either, too busy these days.

**Comment by mehdibenyounes** [comment]
Ok, i await your news.

**Comment by oscarotero** [comment]
Hi.
I've added support to provide your own plural function. For example:

```js
var Translator = require('gettext-translator');
var translations = require('locales/gl.json');

//Set your own plural function
translations.fn = function (n) {
    return n ? 1 : 0;
}

//Load the translations using the provided function instead generate it dinamically.
var i18n = new Translator(translations);
```

Please, let me know if this work for you.
Thanks!

**Comment by mehdibenyounes** [comment]
I had done almost the same thing by replacing the original function. Thank @oscarotero , it's perfect like that!

**Comment by oscarotero** [comment]
v2.1.0 released with this fix. I'm closing this. Thanks!
