### ISSUE TITLE
Can't load translator

### ISSUE THREAD

**Issue by maicol07** [php-gettext/JS-Translator#5]
Hi,
I can't load translator. This is the error message in console:
![immagine](https://user-images.githubusercontent.com/9463142/69496540-5bd81e80-0ed3-11ea-86b2-212358cfee99.png)
This is my code:
```
/*
 * Translation initialization
 */
$.getJSON(ROOTDIR + '/locale/' + USER_LANG + '/messages.json', function (data) {
    window.tr = new Translator(data);
});
var tr;
if (window.tr == null) {
    tr = new Translator()
} else {
    tr = window.tr;
}
```
Note that the translator.js file (dist folder) is included with a <script> tag
Thanks

**Comment by oscarotero** [comment]
Yep.
The new version (3.0.0) only supported CommonJS and ES6 modules. But I just release the 3.0.1 version with UMD support, so now it should work fine to you. Please, update to 3.0.1 and let me know if you have any problem.

**Comment by maicol07** [comment]
Now there is this error:
![immagine](https://user-images.githubusercontent.com/9463142/69539820-8da9bd80-0f85-11ea-88f9-329475fbffd0.png)

**Comment by oscarotero** [comment]
Try this:

```js
const Translator = window.translator.default;
```
